# Generated by Django 6.0.6 on 2026-06-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_value', models.FloatField()),
                ('logins', models.IntegerField()),
                ('days_inactive', models.IntegerField()),
                ('predicted_ltv', models.FloatField()),
                ('churn_risk', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
